### PR TITLE
fix: improve dark mode

### PR DESCRIPTION
**Pull request by Snowfall22**
Addresses #1 

### Features

- Improved Dark mode
- Added nodemon dependency in backend (to make setting up backend easier)

### Screenshot
Screenshot 2023-10-20 183936

### CODE REVIEW

**Comment by Snowfall22** [comment]
@KriteshTimsina please do have a look

**Review by KriteshTimsina — CHANGES_REQUESTED** [review]
Why is the home page and events page white even in dark mode?
image

Request for change:
-Enabling dark mode must apply to all the pages.
-Lyrics page card must make a dark colors to

**Comment by Snowfall22** [comment]
Alright, I'll make the changes.

**Comment by Snowfall22** [comment]
@KriteshTimsina Please do add the hacktoberfest-accepted label to this PR

**Comment by Snowfall22** [comment]
@KriteshTimsina I've added dark mode to all pages. Please have a look and lmk

**Review by KriteshTimsina — APPROVED** [review]
LGTM!

**Pull request merged**
